# Generated by Django 5.1.4 on 2024-12-22 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLedgers',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='EntryQueue',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('column_title', models.CharField(max_length=10, null=True)),
                ('record_ledgers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.recordledgers')),
            ],
            bases=('core.basemodel',),
        ),
    ]
