# Generated by Django 5.1.4 on 2024-12-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryValue',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('entries_value', models.CharField(blank=True, max_length=50, null=True)),
                ('column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.entryqueue')),
            ],
            bases=('core.basemodel',),
        ),
    ]
