# Generated by Django 5.1.4 on 2024-12-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_entryvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryvalue',
            name='column',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entryvaluechild', to='club.entryqueue'),
        ),
    ]
